# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bradford_bazemore/ClionProjects/object_track

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bradford_bazemore/ClionProjects/object_track

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bradford_bazemore/ClionProjects/object_track/CMakeFiles /Users/bradford_bazemore/ClionProjects/object_track/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bradford_bazemore/ClionProjects/object_track/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named object_track

# Build rule for target.
object_track: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 object_track
.PHONY : object_track

# fast build rule for target.
object_track/fast:
	$(MAKE) -f CMakeFiles/object_track.dir/build.make CMakeFiles/object_track.dir/build
.PHONY : object_track/fast

objectTrackingTut.o: objectTrackingTut.cpp.o
.PHONY : objectTrackingTut.o

# target to build an object file
objectTrackingTut.cpp.o:
	$(MAKE) -f CMakeFiles/object_track.dir/build.make CMakeFiles/object_track.dir/objectTrackingTut.cpp.o
.PHONY : objectTrackingTut.cpp.o

objectTrackingTut.i: objectTrackingTut.cpp.i
.PHONY : objectTrackingTut.i

# target to preprocess a source file
objectTrackingTut.cpp.i:
	$(MAKE) -f CMakeFiles/object_track.dir/build.make CMakeFiles/object_track.dir/objectTrackingTut.cpp.i
.PHONY : objectTrackingTut.cpp.i

objectTrackingTut.s: objectTrackingTut.cpp.s
.PHONY : objectTrackingTut.s

# target to generate assembly for a file
objectTrackingTut.cpp.s:
	$(MAKE) -f CMakeFiles/object_track.dir/build.make CMakeFiles/object_track.dir/objectTrackingTut.cpp.s
.PHONY : objectTrackingTut.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... object_track"
	@echo "... rebuild_cache"
	@echo "... objectTrackingTut.o"
	@echo "... objectTrackingTut.i"
	@echo "... objectTrackingTut.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

